# Generated by Django 5.0 on 2023-12-07 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('descriptions', models.JSONField(default=list)),
                ('key_words', models.JSONField(default=list)),
                ('related_entries', models.ManyToManyField(blank=True, to='dict_entry_app.dictionaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('personal_descriptions', models.JSONField(default=list)),
                ('personal_key_words', models.JSONField(default=list)),
                ('global_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict_entry_app.dictionaryentry')),
                ('personal_related_entries', models.ManyToManyField(blank=True, to='dict_entry_app.personaldictionaryentry')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'number')},
            },
        ),
    ]
