# Generated by Django 5.0 on 2023-12-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict_entry_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionaryentry',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='personaldictionaryentry',
            old_name='personal_descriptions',
            new_name='personal_description',
        ),
    ]
