# Generated by Django 5.0 on 2023-12-09 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dict_entry_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldictionaryentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalrelatedentry',
            name='from_personal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='dict_entry_app.personaldictionaryentry'),
        ),
        migrations.AddField(
            model_name='personalrelatedentry',
            name='to_personal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='dict_entry_app.personaldictionaryentry'),
        ),
        migrations.AddField(
            model_name='relatedentry',
            name='from_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='dict_entry_app.dictionaryentry'),
        ),
        migrations.AddField(
            model_name='relatedentry',
            name='to_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='dict_entry_app.dictionaryentry'),
        ),
        migrations.AlterUniqueTogether(
            name='personaldictionaryentry',
            unique_together={('student', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='personalrelatedentry',
            unique_together={('from_personal_entry', 'to_personal_entry')},
        ),
        migrations.AlterUniqueTogether(
            name='relatedentry',
            unique_together={('from_entry', 'to_entry')},
        ),
    ]
