# Generated by Django 5.0 on 2023-12-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict_entry_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionaryentry',
            options={'ordering': ['number']},
        ),
    ]
