# Generated by Django 5.0 on 2023-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_entry_app', '0003_alter_dictionaryentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
