# Generated by Django 5.0 on 2023-12-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_entry_app', '0003_remove_dictionaryentry_related_entries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='number',
            field=models.IntegerField(),
        ),
    ]
