# Generated by Django 5.0 on 2023-12-14 16:49

import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[student_app.validators.validate_student_email]),
        ),
    ]
