# Generated by Django 5.0 on 2023-12-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
